### ISSUE TITLE
Python environment inconsistencies? 

### ISSUE THREAD

**Issue by pervrosen** [HHousen/TransformerSum#39]
I used python3.8 in my conda env that loaded your environment.yml. This seems not to work? I got the following error message. Do you only support a specific python version? Or is it a corrupted env? It seems to be somewhat unrelated to transformersum. What do you think? Thx in advance!

`
> **$python predictions_website.py** 
Traceback (most recent call last):
  File "predictions_website.py", line 7, in <module>
    from extractive import ExtractiveSummarizer
  File "/opt/transformersum/src/extractive.py", line 12, in <module>
    import pytorch_lightning as pl
  File "/opt/anaconda3/envs/transformersum/lib/python3.8/site-packages/pytorch_lightning/__init__.py", line 59, in <module>
    from pytorch_lightning.trainer import Trainer
  File "/opt/anaconda3/envs/transformersum/lib/python3.8/site-packages/pytorch_lightning/trainer/__init__.py", line 18, in <module>
    from pytorch_lightning.trainer.trainer import Trainer
  File "/opt/anaconda3/envs/transformersum/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 32, in <module>
    from pytorch_lightning.loggers import LightningLoggerBase
  File "/opt/anaconda3/envs/transformersum/lib/python3.8/site-packages/pytorch_lightning/loggers/__init__.py", line 59, in <module>
    from pytorch_lightning.loggers.wandb import WandbLogger
  File "/opt/anaconda3/envs/transformersum/lib/python3.8/site-packages/pytorch_lightning/loggers/wandb.py", line 26, in <module>
    import wandb
  File "/opt/anaconda3/envs/transformersum/lib/python3.8/site-packages/wandb/__init__.py", line 37, in <module>
    from wandb import sdk as wandb_sdk
  File "/opt/anaconda3/envs/transformersum/lib/python3.8/site-packages/wandb/sdk/__init__.py", line 12, in <module>
    from .wandb_init import init  # noqa: F401
  File "/opt/anaconda3/envs/transformersum/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 28, in <module>
    from .backend.backend import Backend
  File "/opt/anaconda3/envs/transformersum/lib/python3.8/site-packages/wandb/sdk/backend/backend.py", line 15, in <module>
    from ..internal.internal import wandb_internal
  File "/opt/anaconda3/envs/transformersum/lib/python3.8/site-packages/wandb/sdk/internal/internal.py", line 32, in <module>
    from . import sender
  File "/opt/anaconda3/envs/transformersum/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 17, in <module>
    from wandb.filesync.dir_watcher import DirWatcher
  File "/opt/anaconda3/envs/transformersum/lib/python3.8/site-packages/wandb/filesync/dir_watcher.py", line 7, in <module>
    from watchdog.observers.polling import PollingObserver
  File "/opt/anaconda3/envs/transformersum/lib/python3.8/site-packages/watchdog/observers/__init__.py", line 63, in <module>
    from .inotify import InotifyObserver as Observer
  File "/opt/anaconda3/envs/transformersum/lib/python3.8/site-packages/watchdog/observers/inotify.py", line 74, in <module>
    from .inotify_buffer import InotifyBuffer
  File "/opt/anaconda3/envs/transformersum/lib/python3.8/site-packages/watchdog/observers/inotify_buffer.py", line 20, in <module>
    from watchdog.observers.inotify_c import Inotify
  File "/opt/anaconda3/envs/transformersum/lib/python3.8/site-packages/watchdog/observers/inotify_c.py", line 63, in <module>
    libc = _load_libc()
  File "/opt/anaconda3/envs/transformersum/lib/python3.8/site-packages/watchdog/observers/inotify_c.py", line 43, in _load_libc
    return ctypes.CDLL(libc_path)
  File "/opt/anaconda3/envs/transformersum/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /opt/anaconda3/envs/transformersum/lib/python3.8/site-packages/amp_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda12device_countEv
`

**Comment by HHousen** [comment]
@pervrosen I use Python 3.8.6 in my conda environment. This seems like a corrupted environment, but I'm not sure. Try removing the environment with `conda env remove -n transformersum` and recreating it with `conda env create --file environment.yml`. Let me know if that helps.

**Comment by pervrosen** [comment]
@HHousen - It was indeed a corrupt env. I do not know why since it was newly created. Thx. Cheers!

**Comment by HHousen** [comment]
That's a strange issue. I'm glad you solved it.
